#!/usr/bin/env python3

import rclpy
import gymnasium as gym
from stable_baselines3 import PPO, A2C
from stable_baselines3.common.env_util import make_vec_env
from rosgym.register_env import register_depth_nav_env


def main(args=None):
    rclpy.init(args=args)

    register_depth_nav_env()

    run_name = "SparseNavEnv-A2C-test"

    # Create the environment-DepthNavEnv
    env = make_vec_env("SparseNavEnv-v0", n_envs=1)

    # Create the agent
    model = A2C("CnnPolicy", env, verbose=1, seed=1, tensorboard_log=f"./results/{run_name}", policy_kwargs={"normalize_images": False})

    print("Training start")

    # Train the model
    model.learn(total_timesteps=100000, progress_bar=True)

    # Save the model
    model.save(f"{run_name}.zip")

    # Close the environment
    env.close()

    try:
        if rclpy.ok():
            print("Shutting down ROS 2...")
            rclpy.shutdown()
    except Exception as e:
        print(f"Error during shutdown: {e}")

    return 0

if __name__ == "__main__":
    main()

